services:
  web:
    image:            # reset image
    build: .          # build from sources
    volumes:
      - '.:/app'      # mount application sources from debug
      - '/app/.venv'  # preserve venv created by Dockerfile
    environment:
      - DEBUG=true

  db:
    ports:
      - '5432:5432'

  rabbitmq:
    ports:
      - '5672:5672'

  prometheus:
    ports:
      - '9090:9090'
