name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'


jobs:
  build-and-test:
    uses: ./.github/workflows/tests.yaml
